name: 'Publish a new app version to VTEX'
description: 'Publish a new app version to VTEX'

inputs:
  vtex-app-key:
    description: 'The app key that will be used to call VTEX API'
    required: true
  vtex-app-token:
    description: 'The app token that will be used to call VTEX API'
    required: true
  docker-user:
    description: VTEX Docker username
    required: true
  docker-token:
    description: VTEX Docker token
    required: true
  version-visibility:
    description: 'Indicates the version visibility that will be used: development, unpublished, or published'
    required: false
    default: 'development'
  version-increment-type:
    description: 'Indicates the type of change that is being done, accepting: major, minor, patch'
    required: false
    default: 'patch'

runs:
  using: "composite"
  steps:



