name: 'Publish Docker image to VTEX repo'
description: 'Publish app Docker images to VTEX repository'
inputs:
  app-metadata:
    description: VTEX app metadata extracted with action get-vtex-app-metadata
    required: true
  docker-user:
    description: VTEX Docker username
    required: true
  docker-token:
    description: VTEX Docker token
    required: true
runs:
  using: "composite"
  steps:

    - name: Sets VTEX repository address
      run: echo "REGISTRY=vtexalpha.jfrog.io" >> $GITHUB_ENV
      shell: bash

    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ inputs.docker-user }}
        password: ${{ inputs.docker-token }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: ${{ env.REGISTRY }}/${{ inputs.app-metadata.service-image-name }}
        tags: type=semver,pattern={{raw}},value=${{ inputs.app-metadata.app-version }}

    # Build and push Docker image with Buildx
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: ${{ inputs.app-metadata.service-folder }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
