name: 'Apps Framework API request'
description: 'Execute an API request for Apps Framework API'
inputs:
  request-name:
    description: 'The name of the request'
    required: true
  app-specification:
    description: 'The app specification content'
    required: false
    default: ''
outputs:
  status-code:
    description: 'The status code from the quest'
runs:
  using: 'node12'
  main: 'index.js'
