name: 'Publish an app release to VTEX'
description: 'Publish an app release to VTEX'
runs:
  using: "composite"
  steps:

    - name: Get app metadata
      id: app-metadata
      uses: ./.github/actions/get-vtex-app-metadata

    - name: Build API payload
      id: build-api-payload
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: "yq eval '.' -o json -I 0 vtex.yml"

    - name: Set API request payload
      run: echo API_PAYLOAD='${{steps.build-api-payload.outputs.result}}' >> $GITHUB_ENV
      shell: bash

    - name: Create or update a VTEX service for the service image
      id: call-create-app-release-api
      uses: ./.github/actions/apps-framework-api-request
      with:
        request-name: create-app-release
        app-specification: ${{ env.API_PAYLOAD }}
