name: 'Publish an app release to VTEX'
description: 'Publish an app release to VTEX'
runs:
  using: "composite"
  steps:

    - name: Get app metadata
      id: app-metadata
      uses: vtex/app-metadata-action@main

    - name: Create or update a VTEX service for the service image
      id: call-create-app-release-api
      uses: vtex/apps-framework-request-action@main
      with:
        request-type: create-app-release
        app-specification: ${{steps.app-metadata.outputs.app-specification}}
        wait-app-release-complete: true
