name: 'Get VTEX app metadata'
description: 'Exports VTEX app metadata to the step outputs'
outputs:
  app-id:
    description: "App id"
    value: ${{ steps.get-app-id.outputs.result }}
  app-name:
    description: "App name"
    value: ${{ steps.get-app-name.outputs.result }}
  app-version:
    description: "App version"
    value: ${{ steps.get-app-version.outputs.result }}
  app-specification:
    description: "App specification in JSON format"
    value: ${{ steps.get-app-specification.outputs.result }}
  vendor-id:
    description: "Vendor id"
    value: ${{ steps.get-vendor-id.outputs.result }}
  service-name:
    description: "Service name"
    value: ${{ steps.get-service-folder.outputs.result }}
  service-folder:
    description: "Service folder"
    value: ${{ steps.get-service-folder.outputs.result }}
  service-image-name:
    description: "Service image name"
    value: ${{ steps.get-service-image-name.outputs.result }}
runs:
  using: "composite"
  steps:

    - name: Get app id
      id: get-app-id
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.vendor + "." + .name' 'vtex.yml'

    - name: Get app name
      id: get-app-name
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.name' 'vtex.yml'

    - name: Get app version
      id: get-app-version
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.version' 'vtex.yml'

    - name: Get vendor id
      id: get-vendor-id
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.vendor' 'vtex.yml'

    - name: Get service folder
      id: get-service-folder
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.services[0].folder' 'vtex.yml'

    - name: Get service image name
      id: get-service-image-name
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: yq eval '.services[0].image-name' 'vtex.yml'

    - name: Get app specification
      id: get-app-specification
      uses: mikefarah/yq@v4.13.5
      with:
        cmd: "yq eval '.' -o json -I 0 vtex.yml"
