# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Service Publishing (CD)

on:
  workflow_call:

env:
  APP_VERSION_INCREMENT_TYPE: patch

jobs:
  publish-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This will checkout the PR branch instead of refs/pull/:pr_id/merge
          # It is necessary to avoid a detached HEAD when trying to push updates to the branch
          ref: ${{ github.event.pull_request.head.ref }}

      - name: set-version-visibility-to-unpublished
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: echo "APP_VERSION_VISIBILITY=unpublished" >> $GITHUB_ENV

      - name: set-version-visibility-to-development
        if: ${{ !(github.event_name == 'push' && github.ref_name == 'main') }}
        run: echo "APP_VERSION_VISIBILITY=development" >> $GITHUB_ENV

      - name: Publish app services to VTEX Docker repository
        id: publish-docker-images
        uses: ./.github/actions/publish-docker-image-to-vtex
        with:
          docker-user: ${{ secrets.DOCKER_USER }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          version-visibility: ${{ env.APP_VERSION_VISIBILITY }}
          version-increment-type: ${{ env.APP_VERSION_INCREMENT_TYPE }}
