# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  test-lint:
    name: lint, test, and build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get service folder
        id: getServiceFolder
        uses: mikefarah/yq@v4.11.2
        with:
          cmd: yq eval '.services[0].folder' 'vtex.yml'
      - name: Export env.WORK_DIR as the service path
        run: echo "WORK_DIR=${{ steps.getServiceFolder.outputs.result }}" >> $GITHUB_ENV
      - run: yarn
        working-directory: ${{ env.WORK_DIR }}
      - run: yarn run lint
        working-directory: ${{ env.WORK_DIR }}
      - run: yarn run test
        working-directory: ${{ env.WORK_DIR }}
      - run: yarn run build
        working-directory: ${{ env.WORK_DIR }}
