# On a new tag, it will build the backend service docker image and push it to VTEX repository

name: docker build and push
on:
  push:
    branches: [main]

env:
  REGISTRY: sangalli.jfrog.io

jobs:
  build-on-success:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get backend folder
        id: getBackendFolder
        uses: mikefarah/yq@v4.11.2
        with:
          cmd: yq eval '.backend.folder' 'vtex.yml'

      - name: Get backend image name
        id: getBackendImageName
        uses: mikefarah/yq@v4.11.2
        with:
          cmd: yq eval '.backend.image-name' 'vtex.yml'

      - name: Get app version
        id: getAppVersion
        uses: mikefarah/yq@v4.11.2
        with:
          cmd: yq eval '.version' 'vtex.yml'

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ${{ steps.getBackendFolder.outputs.result }}
          push: true
          tags: ${{ steps.getAppVersion.outputs.result }}
