# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Service CI # test, lint and build js files

defaults:
  run:
    working-directory: ${{ env.WORK_DIR }} # set by getBackendFolder step

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  test-lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get backend folder
        id: getBackendFolder
        uses: mikefarah/yq@v4.11.2
        with:
          cmd: yq eval '.backend.folder' 'vtex.yml'
      - run: echo WORK_DIR=${{ steps.lookupSdkVersion.outputs.result }} >> GITHUB_ENV
      - run: yarn
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
