name: Call a reusable workflow

on: push

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci.yml

  frontend-ci:
    uses: ./.github/workflows/frontend-ci.yml

  publish-frontend-on-success:
    uses: ./.github/workflows/frontend-publish.yml
    needs: [backend-ci, frontend-ci]

  publish-backend-on-success:
    uses: ./.github/workflows/backend-publish.yml
    needs: [backend-ci, frontend-ci]
